### ISSUE TITLE
supervise event-camera calibration

### ISSUE THREAD

**Issue by arrenglover** [robotology/calibration-supervisor#3]
### Overview
EDPR would very much like to use the quality of life functions in `camera-calibration-supervisor` to calibrate 1. event-cameras, and hopefully as a second step 2. event-cameras to RGB cameras (e.g. real-sense). The aim is to have a simple and quick method that people without experience can managed to calibrate the cameras without wasting lots of time.

@vtikha and @arrenglover already discussed.

### Details

We already have methods developed that produce frames from the events which are compatible with opencv `findChessboard()` and other calibration functions and can already do calibration, with some reasonable effort. The biggest problem we typically have faced is that to produce the visual pattern from events we need motion - calibration during motion results in error in corner placement. We have ended up using a screen that can flash the checkerboard to produce the visual pattern, and both the computer screen and camera can remain stationary. If we have a constantly flashing screen the standard module performs detection too often during motion.

As discussed with @vtikha, we hope the simplest solution will be to use a constantly flashing screen (e.g. iPad) and that the positioning requirement of `camera-calibration-supervisor` will only use images taken under relatively stationary conditions. However we have concerns over whether the differing conditions of image production (i.e. the image is produce by events, and is viewing a screen instead of a board) can correctly match the simulated image, as is required. We need to set-up a test together to identify any issues.

If a constantly flashing screen doesn't work, we also discussed having a manual over-ride button of the automatic check of position. The module would still give guidance of the best positions, but instead allow the user to determine when the position has been reached. In addition, the over-ride button could also give an automatic signal to produce a single flash. This is all more work and hopefully not needed.
@ChiaraBartolozzi

The next step is to set-up a time we can test putting everything together?

**Comment by arrenglover** [comment]
@vtikha or @vvasco - I can come in to IIT on Wednesday or Thursday. Can we organise something for this week?

**Comment by vtikha** [comment]
Ciao @arrenglover , unfortunately this week we are overwhelmed with other tasks. We can plan the meeting from next week (15th -19th). Would that be ok?

**Comment by arrenglover** [comment]
of course 15th or 18th is best for me.

**Comment by vtikha** [comment]
The meeting and test has been scheduled for the 18th of February

**Comment by vvasco** [comment]
The following is a summary of the steps taken and what is missing.

### Collecting event dataset 

During the tests we did with @vtikha @arrenglover @GiuliaDAngelo @ilaria-carlini and @lauracavaliere  on February 18th, we came out with these parameters to produce a nice event image:

- `vPreProcess --flipy --filter_temporal false --filter_spatial false --sf_tsize 0.05 --split_stereo`
- `vFramerLite --displays "(/left (BLACK) /right (BLACK))" --frameRate 30 --eventWindow 0.1`

### Detecting corners on the event image

With @ilaria-carlini and @lauracavaliere we updated `calibSupervisor` in order to:
- **filter out** the event image to remove background noise and fill holes;
- add a check that ensures that the image sent to `stereoCalib` is **good for detecting corners** (if stereo calibration is active, the check is done on left and right images)

### Output 

This is the output we have using the dataset we collected:

https://user-images.githubusercontent.com/9716288/109295411-0190e080-782f-11eb-977d-4346178ba06a.mp4

_On the left_: output of `calibSupervisor`, with **detected corners** and **green bounding box** when the image is good
_On the right_: output of `stereoCalib`, with **detected corners**

### To do

We finally need to test out the whole pipeline on `iCubGenova02`

**Comment by GiuliaDAngelo** [comment]
Thanks @vvasco ! 
When do you want to test the pipeline? Should we arrange a meeting?

**Comment by vtikha** [comment]
Ciao @GiuliaDAngelo,

what do you say about the morning of Wednesday the 3rd of March ?

**Comment by GiuliaDAngelo** [comment]
@vtikha Fine to me! 
@arrenglover would you be available?

**Comment by arrenglover** [comment]
nice work. sure for Wednesday.

**Comment by GiuliaDAngelo** [comment]
@vvasco , @vtikha , @arrenglover Wednesday 9:30? 
I'm going to book the robot!

**Comment by vtikha** [comment]
Great thank you

**Comment by vvasco** [comment]
We successfully manage to run the entire pipeline on iCubGenova02.
The **stereo** calibration works properly as we can see from the following images:

![3](https://user-images.githubusercontent.com/9716288/110301077-f476ad00-7ff7-11eb-8241-2c519f57677f.png)

_left column_ :  _raw images_ 
_right column_ : _calibrated images_

**Comment by GiuliaDAngelo** [comment]
Thanks @vvasco!
I look forward to testing it with you :) 
I'll go ahead installing the drivers for the RGB camera, then we can try to calibrate the RGB with the ATIS.

**Comment by vtikha** [comment]
Ciao @GiuliaDAngelo, this was never really clear to us, and during a f2f update with @arrenglover (and @ChiaraBartolozzi) it came out that the task you want to do actually falls outside the scope of this project and further development needs to be made `ad-hoc` to achieve what you require. I see two possibile ways:

1. You retrieve the CAD of the positions of the cameras and camera details, then gazebo and the position evaluation pipeline are modified to account for this specific case. Once the supervised positions are retrieved, run this pipeline to calibrate the cameras. Then one needs to figure out the `roto-transformation` between the cameras.  
If the positions of the cameras are changed then everything needs to start from scratch.

2. Since @arrenglover mentioned that the supervision **is not** even needed but **only** the installation / modification of the ini files (just even our simple script [here](https://github.com/robotology/camera-calibration-supervisor/blob/main/app/modify-params.sh)) you can run the calibration with the board as you see fit and then figure out the `roto-transformation` between the cameras. 

With regards to **this** issue and request, we can **close** it as we were successful in modifying all the code and pipeline to include the calibration of the `event-driven` cameras of the robot. 

As previously mentioned, as your goal is for a very particular case, we should make a separate project if needed.

**Comment by ChiaraBartolozzi** [comment]
Ciao @vtikha and @vvasco 

first of all, let me thank you for your work and good results :-)

I agree that the goal of having the script for the installation was useful (as mentioned by @arrenglover), but I believe the scope of the method for calibration supervision is still extremely important to us, to have a method that allows for a robust and precise calibration in a short time.

With regards to @GiuliaDAngelo 's request, a possible way to proceed is to check if we can run the calibration between events and RGB without the supervision. If we understand that this does not achieve good results, we'll try to resort to the supervision method and possibly open a new issue to ask for help.
